version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "16:00"
  open-pull-requests-limit: 12
  target-branch: 2.x-develop
  reviewers:
  - pandaskii
