services:
  ##########################################
  # govcms: The GovCMS local development
  ##########################################
  govcms:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.govcms
      secrets:
       - github_token
    ports:
      - 8888:80
    volumes:
      - /root/.composer
      - /var/www/html/sites
      - $PWD/web/develop/modules:/app/web/modules/develop
      - $PWD/web/develop/themes:/app/web/themes/develop
      #- $PWD/web/develop/profiles:/app/web/profiles
    environment:
      GITHUB_TOKEN: /run/secrets/github_token
    secrets:
       - github_token

  ##########################################
  # mariadb: The database used by local
  ##########################################
  mariadb:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: drupal
      MARIADB_USER: drupal
      MARIADB_PASSWORD: drupal
    volumes:
      - $PWD/web/develop/database:/var/lib/mysql

secrets:
   github_token:
     file: $PWD/.docker/auth.json

networks:
  default:
    external: false
