version: '2.3'

x-volumes:
  &default-volumes
    volumes:
      - files:/app/web/sites/default/files

x-environment:
  &default-environment
    LAGOON_ROUTE: ${LOCALDEV_URL:-http://govcms-poc.docker.amazee.io}

volumes:
  files: {}

services:

  cli: # cli container, will be used for executing composer and any local commands (drush, drupal, etc.)
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.govcms
    image: ${DOCKERHUB_NAMESPACE:-govcmspoc}/govcms
    << : *default-volumes # loads the defined volumes from the top
    environment:
      << : *default-environment

  test:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.test
      args:
        CLI_IMAGE: ${DOCKERHUB_NAMESPACE:-govcmspoc}/govcms
    image: ${DOCKERHUB_NAMESPACE:-govcmspoc}/test
    << : *default-volumes
    depends_on:
      - cli
    environment:
      << : *default-environment

  nginx:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.nginx-drupal
      args:
        CLI_IMAGE: ${DOCKERHUB_NAMESPACE:-govcmspoc}/govcms
    image: ${DOCKERHUB_NAMESPACE:-govcmspoc}/nginx-drupal
    << : *default-volumes
    environment:
      << : *default-environment
    networks:
      - amazeeio-network
      - default

  php:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.php
      args:
        CLI_IMAGE: ${DOCKERHUB_NAMESPACE:-govcmspoc}/govcms
    image: ${DOCKERHUB_NAMESPACE:-govcmspoc}/php
    << : *default-volumes
    environment:
      << : *default-environment

  mariadb:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.mariadb-drupal
    image: ${DOCKERHUB_NAMESPACE:-govcmspoc}/mariadb-drupal
    ports:
      - "3306" # Find port on host with `docker-compose port mariadb 3306`
    environment:
      << : *default-environment

  solr:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.solr
      args:
        CLI_IMAGE: ${DOCKERHUB_NAMESPACE:-govcmspoc}/govcms
    image: ${DOCKERHUB_NAMESPACE:-govcmspoc}/solr
    ports:
      - "8983" # Find port on host with `docker-compose port solr 8983`
    environment:
      << : *default-environment

  chrome:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.chrome
    image: selenium/standalone-chrome
    shm_size: '1gb'
    depends_on:
      - test
    << : *default-volumes

networks:
  amazeeio-network:
    external: true
