name: Custom Permissions
type: module
description: 'Allows additional permissions. [Drupal 10 compatibility]'
package: GovCMS [Drupal 10 compatibility]
core_version_requirement: ^9 || ^10
lifecycle: deprecated
lifecycle_link: 'https://github.com/GovCMS/GovCMS'
